# Generated by Django 3.0.8 on 2020-07-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='team_members',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
