# Generated by Django 3.0.8 on 2020-07-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_registration_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.TextField()),
                ('team', models.TextField()),
            ],
        ),
    ]
